stop scalactic being added as an unnecessary runtime dependency
https://github.com/guardian/frontend/pull/24833
Scalactic version conflicts were causing compilation failures when compiling tests in frontend

```
java.lang.NoSuchMethodError: 'void org.scalactic.BooleanMacro.<init>(scala.reflect.macros.whitebox.Context, java.lang.String)'
```